feat(Error): Rewrite Error stack frames to include zone
The errors caused by the Zone contain extra stack frames. This feature
removes the confusing stack frames as well as appends the zone for each
stack frame to get a better understanding of the error messages.

Improved Error:
```
Error.spec.js:54 Error: Inside [InnerZone]
    at insideRun (Error.spec.js:31) [InnerZone]
    at Zone.run (zone.js:100) [<root> => InnerZone]
    at testFn (Error.spec.js:29) [<root>]
    at Zone.run (zone.js:100) [ProxyZone => <root>]
    at Object.eval (Error.spec.js:19) [ProxyZone]
```

Original Error:
```
Error.spec.js:53 Error: Inside
    at ZoneAwareError (zone.js:652)
    at insideRun (Error.spec.js:31)
    at ZoneDelegate.invoke (zone.js:216)
    at Zone.run (zone.js:100)
    at testFn (Error.spec.js:29)
    at ZoneDelegate.invoke (zone.js:216)
    at Zone.run (zone.js:100)
    at Object.eval (Error.spec.js:19)
```